// <auto-generated />
namespace AU_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class EditYear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditYear));
        
        string IMigrationMetadata.Id
        {
            get { return "201510230850198_EditYear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
